global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # MinIO — running in Docker network, use service name
  - job_name: "minio"
    static_configs:
      - targets: ["minio:9000"]
    metrics_path: /minio/v2/metrics/cluster
    bearer_token: "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoibWluaW9hZG1pbiIsImV4cCI6NDkzMjA4MzU4Nn0.6hYy0guxbgGyG0e17LpH5m31MJfRDmsQ9XhLWdnHnraYHDxozUO92MsLj9Az06JsfHrvfqU2f451JAq3Dt3kDw"

  # faasd-provider — running on WSL host, use network gateway IP
  - job_name: "faasd-provider"
    static_configs:
      - targets: ["172.19.0.1:8081"]
    metrics_path: /metrics

  # FastAPI gateway — running in Docker network, use service name
  - job_name: "fastapi-gateway"
    static_configs:
      - targets: ["gateway:5000"]
    metrics_path: /metrics
